### ISSUE TITLE
Suggestion: A Config to enable/disable items carrying over between games

### ISSUE THREAD

**Issue by Nick56731** [Skydust2B/PersistentPurchasesRewritten#3]
Example: I want to have the Signal Translator from the start but it doesnt get saved so maybe there could be a config in which you mark what will remain over games or which will get thrown out when you miss quota

**Comment by Skydust2B** [comment]
Hello!
This is already possible in the config files but this mod doesn’t support keeping non-cosmetic items which is why you can’t save the signal translator.

I’m not planning to support keeping these items for now.
